# NumPy Arrays

----------

In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]
list1

[1, 2, 3]

In [3]:
type(list1)

list

In [4]:
array1 = np.array(list1)
array1

array([1, 2, 3])

In [5]:
type(array1)

numpy.ndarray

np.arrange creates integer

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

np.zeros creates float

In [8]:
np.zeros(shape=(5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Create an array with 2 rows and 4 columns

In [9]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.random.seed(101)
array2 = np.random.randint(0, 100, 10)

In [11]:
array2

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [12]:
array2.max()

95

argmax() turns the index location of the maximum value in the array

In [13]:
array2.argmax()

0

In [14]:
array2.min()

9

argmin() turns the index location of the minimum value in the array

In [15]:
array2.argmin()

7

In [16]:
array2.mean()

60.8

Reshape array2 to two rows and 5 columns

In [17]:
array2.reshape((2,5))

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [18]:
matrix = np.arange(0, 100).reshape(10, 10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
matrix.shape

(10, 10)

In [20]:
row = 3
col = 5
matrix[row, col]

35

The code below, returns the every value in the particular column

In [30]:
matrix[:,6]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [31]:
matrix[:,6].reshape(10,1)

array([[ 6],
       [16],
       [26],
       [36],
       [46],
       [56],
       [66],
       [76],
       [86],
       [96]])

Returns every value in a specific row

In [32]:
matrix[3,:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [33]:
matrix[0:3, 0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [34]:
new_matrix = matrix.copy()
new_matrix[5:9, 3:6] = 0
new_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52,  0,  0,  0, 56, 57, 58, 59],
       [60, 61, 62,  0,  0,  0, 66, 67, 68, 69],
       [70, 71, 72,  0,  0,  0, 76, 77, 78, 79],
       [80, 81, 82,  0,  0,  0, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
new_matrix[0:5, :] = 111
new_matrix

array([[111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [111, 111, 111, 111, 111, 111, 111, 111, 111, 111],
       [ 50,  51,  52,   0,   0,   0,  56,  57,  58,  59],
       [ 60,  61,  62,   0,   0,   0,  66,  67,  68,  69],
       [ 70,  71,  72,   0,   0,   0,  76,  77,  78,  79],
       [ 80,  81,  82,   0,   0,   0,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])